version: '3.8'

services:
   indexer:     
     image: terraclassic.indexer
     build: 
      context: .
      dockerfile: Dockerfile
      labels:
       - "terraclassic.indexer.description=Contains everything needed to run the FCD application"
   indexer-collector:     
     image: terraclassic.indexer-collector
     build: 
      context: .
      dockerfile: Dockerfile.terraclassic.indexer-collector
      args:
        base_image: terraclassic.indexer
      labels:
        - "terraclassic.indexer-collector.description=Contains everything needed to run the FCD collector"
   indexer-api:
     image: terraclassic.indexer-api
     build: 
       context: .
       dockerfile: Dockerfile.terraclassic.indexer-api
       args:
         base_image: terraclassic.indexer
       labels:
        - "terraclassic.indexer-api.description=Contains everything needed to run the FCD API"